---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Configure selinux | selinux-01
  selinux:
    policy: "{{ os_selinux_policy }}"
    state: "{{ os_selinux_state }}"
  when:
    - "'libselinux' in ansible_facts.packages"
    - "'libselinux-python' in ansible_facts.packages"
    - "'policycoreutils-python' in ansible_facts.packages"
